CREATE DATABASE IF NOT EXISTS login_register;

USE login_register

CREATE TABLE IF NOT EXISTS usuarios(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    passwd VARCHAR(255) NOT NULL
)